[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glorious-prompt-server"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "chromadb",
    "sentence-transformers"
]